// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#if GNOME
namespace Gnome {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum DesktopThumbnailSize {

		Normal,
		Large,
	}
#endregion
}
#endif
